// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

// Wifi home
//#define IOT_CONFIG_WIFI_SSID "dlink-A3E418"
//#define IOT_CONFIG_WIFI_PASSWORD "gmbwg8w7n79"

// Wifi config laptop (hotspot)
#define IOT_CONFIG_WIFI_SSID "081-1-K3N081 8507"
#define IOT_CONFIG_WIFI_PASSWORD "5>Q19b57"

// Wifi config mobile (hotspot)
//#define IOT_CONFIG_WIFI_SSID "NokiaG21"
//#define IOT_CONFIG_WIFI_PASSWORD "Bullet66!"

// Enable macro IOT_CONFIG_USE_X509_CERT to use an x509 certificate to authenticate the IoT device.
// The two main modes of authentication are through SAS tokens (automatically generated by the
// sample using the provided device symmetric key) or through x509 certificates. Please choose the
// appropriate option according to your device authentication mode.

// #define IOT_CONFIG_USE_X509_CERT

#ifdef IOT_CONFIG_USE_X509_CERT

/*
 * Please set the define IOT_CONFIG_DEVICE_CERT below with
 * the content of your device x509 certificate.
 *
 * Example:
 * #define IOT_CONFIG_DEVICE_CERT "-----BEGIN CERTIFICATE-----\r\n" \
 * "MIIBJDCBywIUfeHrebBVa2eZAbouBgACp9R3BncwCgYIKoZIzj0EAwIwETEPMA0G\r\n" \
 * "A1UEAwwGRFBTIENBMB4XDTIyMDMyMjazMTAzN1oXDTIzMDMyMjIzMTAzN1owGTEX\r\n" \
 * "MBUGA1UEAwwOY29udG9zby1kZXZpY2UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\r\n" \
 * .......
 * "YmGzdaHTb6P1W+p+jmc+jJn1MAoGCXqGSM49BAMCA0gAMEUCIEnbEMsAdGFroMwl\r\n" \
 * "vTfQahwsxN3xink9z1gtirrjQlqDAiEAyU+6TUJcG6d9JF+uJqsLFpsbbF3IzGAw\r\n" \
 * "yC+koNRC0MU=\r\n" \
 * "-----END CERTIFICATE-----"
 *
 */
#define IOT_CONFIG_DEVICE_CERT "Device Certificate"

/*
 * Please set the define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY below with
 * the content of your device x509 private key.
 *
 * Example:
 *
 * #define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "-----BEGIN EC PRIVATE KEY-----\r\n" \
 * "MHcCAQEEIKGXkMMiO9D7jYpUjUGTBn7gGzeKPeNzCP83wbfQfLd9obAoGCCqGSM49\r\n" \
 * "AwEHoUQDQgAEU6nQoYbjgJvBwaeD6MyAYmOSDg0QhEdyyV337qrlIbDEKvFsn1El\r\n" \
 * "yRabc4dNp2Jhs3Xh02+j9Vvqfo5nPoyZ9Q==\r\n" \
 * "-----END EC PRIVATE KEY-----"
 *
 * Note the type of key may different in your case. Such as BEGIN PRIVATE KEY
 * or BEGIN RSA PRIVATE KEY.
 *
 */
#define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "Device Certificate Private Key"

#endif // IOT_CONFIG_USE_X509_CERT

// Azure IoT
//#define IOT_CONFIG_IOTHUB_FQDN "IoTHub-wolf66.azure-devices.net" // my iothub & blob storage
//#define IOT_CONFIG_DEVICE_ID "pico1" // my iothub & blob storage
#define IOT_CONFIG_IOTHUB_FQDN "iot-sensor-iot-hub.azure-devices.net" // georges iothub & database
#define IOT_CONFIG_DEVICE_ID "sim-raspberry-pi" // georges iothub & database
// Use device key if not using certificates
#ifndef IOT_CONFIG_USE_X509_CERT
//#define IOT_CONFIG_DEVICE_KEY "UzDxUyoMYQHcPj4rXd3K9k9Mcui9FPw4v0ImyEBg6eg=" // my iothub & blob storage
#define IOT_CONFIG_DEVICE_KEY "TXWwqyQu6Bx3zUl5dvgOIv/5+EJASYz5iAIoTI7Cu/E="  // georges iothub & database
#endif // IOT_CONFIG_USE_X509_CERT

// Publish 1 message every 15 seconds (15 = 4 per minute, which is 240 per hour, which is 5760 per day (LIMIT is 8000 messaegs per day for FREE TIER))
#define TELEMETRY_FREQUENCY_MILLISECS 15000
